blank_issues_enabled: false
contact_links:
  - name: Papaplatte
    url: https://papaplatte.de
    about: Die hier angezeigten Vorlagen sollten genutzt werden. Falls euer Anliegen nicht mit einem der Vorlagen abgedeckt sein sollte, kontaktiert uns bitte über unsere Webseite.
